### ISSUE TITLE
-215:Assertion failed

### ISSUE THREAD

**Issue by swiftDoer** [vt-vl-lab/3d-photo-inpainting#190]
Wanted to try out inpainting on Google colab. Get the following error at the last step: 

 processing patch 54 | [960   0 197 197]
	 processing patch 55 | [1034    0  197  197]
finished
  0% 0/1 [00:53<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    image = cv2.resize(image, (config['output_w'], config['output_h']), interpolation=cv2.INTER_AREA)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:3688: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

**Comment by SlimeVRX** [comment]
I found a Colab solution [here](https://twitter.com/0scartong/status/1623133283298217984), it works with Python 3.8
